name: Run Rumi Quote Bot Daily

on:
  schedule:
    - cron: '11 11 * * *'  # Runs at 11:11 AM UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Adds a timeout to ensure the job doesn't run for too long

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Using a stable LTS version

      - name: Install dependencies
        run: npm install

      - name: Run the bot
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: node bot.js

      - name: Commit updated used-quotes.json
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add used-quotes.json
          git diff --staged --quiet || git commit -m "Update used-quotes.json [skip ci]"
          git push